name: Publish Helm chart

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  CHART_DIR: .
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Push chart
        shell: bash
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_LC=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          mkdir -p packaged
          TGZ=$(helm package "${CHART_DIR}" --destination packaged | awk '{print $NF}')
          helm push "$TGZ" "oci://${REGISTRY}/${OWNER_LC}/${REPO_LC}"
